package se.axelkarlsson.passpicker.ui.route.generator

import androidx.compose.foundation.background
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.wrapContentWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import se.axelkarlsson.passpicker.R
import se.axelkarlsson.passpicker.ui.component.CheckboxRow
import kotlin.math.roundToInt

@Composable
private fun GeneratePasswordFloatingActionButton(onClick: () -> Unit) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp), contentAlignment = Alignment.BottomEnd
    ) {
        FloatingActionButton(onClick = onClick) {
            Icon(
                painter = painterResource(R.drawable.refresh_24px),
                contentDescription = "New Password"
            )
        }
    }
}

@Composable
private fun GeneratedPasswordRow(
    password: String, onCopyPassword: () -> Unit, onPasswordVisibilityToggled: () -> Unit,
    passwordVisible: Boolean
) {
    Row(
        modifier = Modifier
            .clip(shape = RoundedCornerShape(16.dp))
            .fillMaxWidth()
            .background(color = MaterialTheme.colorScheme.surfaceContainer)
            .combinedClickable(onClick = {}, onLongClick = {}),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text(
            modifier = Modifier
                .weight(1f)
                .padding(start = 8.dp),
            text = if (passwordVisible) {
                password
            } else {
                var str = ""
                for (i in 1..password.length) str += "*"

                str
            },
            fontFamily = FontFamily.Monospace,
            overflow = TextOverflow.Ellipsis,
            maxLines = 1,
            fontWeight = if (passwordVisible) {
                FontWeight.Normal
            } else {
                FontWeight.Bold
            }
        )

        Row(
            modifier = Modifier.wrapContentWidth()
        ) {
            IconButton(onClick = onPasswordVisibilityToggled) {
                if (passwordVisible) {
                    Icon(
                        painter = painterResource(R.drawable.visibility_off_24px),
                        contentDescription = "Hide Password"
                    )
                } else {
                    Icon(
                        painter = painterResource(R.drawable.visibility_24px),
                        contentDescription = "Show Password"
                    )
                }

            }

            IconButton(onClick = onCopyPassword) {
                Icon(
                    painter = painterResource(R.drawable.content_copy_24px),
                    contentDescription = "Copy Generated Password"
                )
            }
        }
    }
}

@Composable
fun GeneratorScreen(
    viewModel: GeneratorViewModel = hiltViewModel()
) {
    val generated by viewModel.generated.collectAsStateWithLifecycle()
    val passwordLength = viewModel.length.collectAsStateWithLifecycle()

    val passwordVisible by viewModel.visible.collectAsStateWithLifecycle()

    val useAlpha by viewModel.useAlpha.collectAsStateWithLifecycle()
    val useNumeric by viewModel.useNumeric.collectAsStateWithLifecycle()
    val useSpecial by viewModel.useSpecial.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.generate()
    }

    GeneratePasswordFloatingActionButton({ viewModel.generate() })

    Column(
        modifier = Modifier.padding(28.dp)
    ) {
        GeneratedPasswordRow(
            generated,
            { viewModel.onCopyPassword() },
            { viewModel.onPasswordVisibilityToggled() },
            passwordVisible
        )

        Column(modifier = Modifier.padding(top = 16.dp)) {
            Text("Options", fontSize = 20.sp)

            Column(modifier = Modifier.padding(top = 16.dp)) {
                Text("Password Length (${passwordLength.value.roundToInt()})")

                Slider(
                    value = passwordLength.value,
                    valueRange = viewModel.minimum.toFloat()..viewModel.maximum.toFloat(),
                    onValueChange = {
                        viewModel.onSliderValueChanged(it)
                    })
            }

            CheckboxRow(
                checked = useAlpha,
                onCheck = { viewModel.onChecked("alpha", it) },
                label = "Alphabetic"
            )
            CheckboxRow(
                checked = useNumeric,
                onCheck = { viewModel.onChecked("numeric", it) },
                label = "Numeric"
            )
            CheckboxRow(
                checked = useSpecial,
                onCheck = { viewModel.onChecked("special", it) },
                label = "Special"
            )
        }
    }
}